// Generated by CoffeeScript 1.6.2
(function() {
  var FeedStore, LocalStorage, get_key, store;

  LocalStorage = require("node-localstorage").LocalStorage;

  global.localStorage = new LocalStorage('storage');

  store = require("store");

  get_key = function(collection, key) {
    return collection + "-" + key;
  };

  FeedStore = (function() {
    function FeedStore() {}

    FeedStore.prototype.initialize = function() {
      return console.log("FeedStore ctor");
    };

    FeedStore.prototype.add = function(params) {
      this.c = params.collection;
      this.k = params.key;
      this.v = params.value;
      return store.set(get_key(this.c, this.k), this.v);
    };

    FeedStore.prototype.find = function(params) {
      this.c = params.collection;
      this.k = params.key;
      return store.get(get_key(this.c, this.k));
    };

    return FeedStore;

  })();

  module.exports = new FeedStore();

}).call(this);
