// Generated by CoffeeScript 1.6.2
(function() {
  var FEEDS_COLL, RssfeedLocal, feed_store, _;

  feed_store = require('./feed-store');

  _ = require('underscore');

  FEEDS_COLL = 'feeds';

  RssfeedLocal = (function() {
    function RssfeedLocal() {
      this.requires_login = false;
      this.logged_in = false;
      this.token1 = void 0;
      this.token2 = void 0;
    }

    RssfeedLocal.prototype.login = function(token1, token2, callback) {
      var err;

      err = void 0;
      if (this.token1 === token1 && this.token2 === token2) {
        this.logged_in = true;
      } else {
        this.logged_in = false;
        err = "login failed";
      }
      return typeof callback === "function" ? callback(err) : void 0;
    };

    RssfeedLocal.prototype.setLogin = function(token1, token2) {
      this.token1 = token1;
      return this.token2 = token2;
    };

    RssfeedLocal.prototype.feeds = function(callback) {
      var feed_urls;

      if (this.requires_login === true && this.logged_in === false) {
        return typeof callback === "function" ? callback(new Error("boo"), void 0) : void 0;
      } else {
        feed_urls = feed_store.find_all({
          collection: FEEDS_COLL
        });
        return typeof callback === "function" ? callback(void 0, _.values(feed_urls)) : void 0;
      }
    };

    RssfeedLocal.prototype.add = function(feed_url, callback) {
      if (this.requires_login === true && this.logged_in === false) {
        return typeof callback === "function" ? callback(new Error("boo"), void 0) : void 0;
      } else {
        feed_store.add({
          collection: FEEDS_COLL,
          key: 1,
          value: {
            feed_url: feed_url
          }
        });
        return typeof callback === "function" ? callback() : void 0;
      }
    };

    RssfeedLocal.prototype.requiresLogin = function() {
      return this.requires_login;
    };

    RssfeedLocal.prototype.setRequiresLogin = function(requires_login) {
      return this.requires_login = requires_login;
    };

    RssfeedLocal.prototype.clear = function(callback) {
      if (this.requires_login === true && this.logged_in === false) {
        return typeof callback === "function" ? callback(new Error("boo"), void 0) : void 0;
      } else {
        feed_store.clear();
        return typeof callback === "function" ? callback() : void 0;
      }
    };

    return RssfeedLocal;

  })();

  module.exports = new RssfeedLocal();

}).call(this);
