// Generated by CoffeeScript 1.6.2
(function() {
  var RssfeedLocal;

  RssfeedLocal = (function() {
    function RssfeedLocal() {
      this.requires_login = false;
      this.logged_in = false;
      this.token1 = void 0;
      this.token2 = void 0;
    }

    RssfeedLocal.prototype.login = function(token1, token2, callback) {
      var err;

      err = void 0;
      if (this.token1 === token1 && this.token2 === token2) {
        this.logged_in = true;
      } else {
        this.logged_in = false;
        err = "login failed";
      }
      return typeof callback === "function" ? callback(err) : void 0;
    };

    RssfeedLocal.prototype.setLogin = function(token1, token2) {
      this.token1 = token1;
      return this.token2 = token2;
    };

    RssfeedLocal.prototype.feeds = function(callback) {
      console.log("feeds called");
      if (this.requires_login === true && this.logged_in === false) {
        return typeof callback === "function" ? callback(new Error("boo"), void 0) : void 0;
      } else {
        return typeof callback === "function" ? callback(void 0, []) : void 0;
      }
    };

    RssfeedLocal.prototype.requiresLogin = function() {
      return this.requires_login;
    };

    RssfeedLocal.prototype.setRequiresLogin = function(requires_login) {
      return this.requires_login = requires_login;
    };

    return RssfeedLocal;

  })();

  module.exports = new RssfeedLocal();

}).call(this);
